
services:
  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api/
      - NEXT_PUBLIC_PORT=8080

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5431/mentors?schema=public
      - PORT=3000
      - ORIGIN=http://localhost:8080
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres
    environment:
      - POSTGRES_PORT=5431
      - PGPORT=5431
      - POSTGRES_DB=mentors
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5431:5431"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5