version: '3.8'

services:
  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api/
      - NEXT_PUBLIC_PORT=8080

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@localhost:5432/mentors?schema=public
      - PORT=3000
      - ORIGIN=http://localhost:8080

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=mentors
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"