# Use official Node.js image as base
FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY webapp/package.json webapp/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY webapp .

# Build the application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start:dev"]
