# Use official Node.js image as base
FROM node:14-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY api/package.json api/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY api .

# Expose port 4000
EXPOSE 4000

# Start the application
CMD ["npm", "run", "start:dev"]
