
FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3000

COPY migrate-and-start.sh /opt/src/scripts/migrate-and-start.sh

CMD /opt/src/scripts/migrate-and-start.sh
